"""User table

Revision ID: e13c9de122e1
Revises: 
Create Date: 2018-03-04 12:10:08.692900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13c9de122e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('acc_no', sa.String(length=255), nullable=False),
    sa.Column('acc_name', sa.String(length=255), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=True),
    sa.Column('date', sa.String(length=25), nullable=True),
    sa.Column('who', sa.Enum('crtr', 'intx', 'intxx', name='who_enum'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ready', 'queued', 'buyer', 'stockholder', 'seller', 'frozen', name='status_enum'), nullable=False),
    sa.Column('notice', sa.String(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_acc_no'), 'user', ['acc_no'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_acc_no'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
